CREATE DATABASE IF NOT EXISTS ARSnipper;

USE ARSnipper;


CREATE TABLE IF NOT EXISTS USERS(
    C_FIRST_NAME VARCHAR(255) NOT NULL,
    C_LAST_NAME VARCHAR(255) NOT NULL,
    C_EMAIL VARCHAR(255) NOT NULL PRIMARY KEY,
    C_PHONE VARCHAR(255) NOT NULL,
);

CREATE TABLE IF NOT EXISTS ACCOUNTS(
    C_EMAIL VARCHAR(255) NOT NULL,
    C_PASSWORD VARCHAR(255) NOT NULL,
    C_SALT VARCHAR(255) NOT NULL,
    Foreign Key (C_EMAIL) REFERENCES USERS(C_EMAIL),
    PRIMARY KEY (C_EMAIL,C_SALT)
);



CREATE TABLE IF NOT EXISTS USER_IMAGE(
    IMAGE_CODE TEXT NOT NULL,
    C_EMAIL VARCHAR(255) NOT NULL,
    OBJECT_CODE TEXT NOT NULL,
    Foreign Key (C_EMAIL) REFERENCES USERS(C_EMAIL),
    PRIMARY KEY (IMAGE_CODE,C_EMAIL, OBJECT_CODE)
);


CREATE TABLE IF NOT EXISTS IMAGES(
    IMAGE_CODE TEXT NOT NULL,
    IMAGE_OBJECT TEXT NOT NULL,
    PRIMARY KEY (IMAGE_CODE, IMAGE_OBJECT)
);

CREATE TABLE IF NOT EXISTS IMAGE_OBJECTS(
    IMAGE_CODE TEXT NOT NULL,
    OBJECT_CODE TEXT NOT NULL,
    PRIMARY KEY (IMAGE_CODE, OBJECT_CODE)
);

CREATE TABLE IF NOT EXISTS OBJECTS(
    OBJECT_CODE TEXT NOT NULL PRIMARY KEY,
    OBJECT_DATA TEXT NOT NULL
);
